# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: ChatQnA-E2E-test

on:
  pull_request:
    # pull_request_target:
    branches: [main]
    types: [opened, reopened, ready_for_review, synchronize] # added `ready_for_review` since draft is skipped
    paths:
      - ChatQnA/ui/**
      - "!**.md"
      - .github/workflows/ChatQnA_E2E.yml
  workflow_dispatch:

# If there is a new commit, the previous jobs will be canceled
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ChatQnA:
    runs-on: aise-cluster
    strategy:
      matrix:
        job_name: ["langchain"]
      fail-fast: false
    steps:
      - name: Clean Up Working Directory
        run: sudo rm -rf ${{github.workspace}}/*

      - name: Checkout out Repo
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: Run E2E Test
        env:
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
        run: |
          cd ${{ github.workspace }}/ChatQnA/deprecated/tests
          export TEST_FRONTEND="true"
          bash test_${{ matrix.job_name }}_inference.sh

      - name: Publish pipeline artifact
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.job_name }}
          path: ${{ github.workspace }}/ChatQnA/deprecated/tests/E2E_tests
